[program:smart-scheduler-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/ameenullah/Documents/smart-scheduler-system/artisan queue:work database --sleep=3 --tries=3 --max-time=3600 --queue=default
directory=/home/ameenullah/Documents/smart-scheduler-system
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=ameenullah
numprocs=2
redirect_stderr=true
stdout_logfile=/home/ameenullah/Documents/smart-scheduler-system/storage/logs/worker.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3
stopwaitsecs=3600
